---1
ALTER TABLE HOATDONG ADD PRIMARY KEY (TENDD, TENHOATDONG);
ALTER TABLE HOATDONG ADD FOREIGN KEY (TENDD) REFERENCES DIADIEM(TENDD);
ALTER TABLE DIADIEM ADD UNIQUE (TPHO, VUNG);

----2
SELECT HOKH, TENKH
FROM KHACHHANG
WHERE VUNG = 'Europe';

----3
SELECT DISTINCT DD.VUNG
FROM KHACHHANG KH
JOIN KYNGHI KN ON KH.IDKH = KN.IDKH
JOIN DIADIEM DD ON DD.TENDD = KN.TENDD
WHERE KH.HOKH = 'Kerouac' AND KH.TENKH = 'Jack';

----4
SELECT TENDD, TPHO
FROM DIADIEM
WHERE TENDD IN (
	SELECT DD.TENDD
	FROM HOATDONG HD
	JOIN DIADIEM DD ON HD.TENDD = DD.TENDD
	GROUP BY DD.TENDD HAVING COUNT(*) >=2);
	
-----5
SELECT TENKH
FROM KHACHHANG
WHERE IDKH NOT IN (
	SELECT KH.IDKH
	FROM KYNGHI KN
	JOIN DIADIEM DD ON KN.TENDD = DD.TENDD
	WHERE DD.VUNG != 'Europe'
	);
	
	
----6
SELECT TENDD
FROM KYNGHI
GROUP BY TENDD HAVING COUNT(*) = (
	SELECT MAX(COUNT(TENDD))
	FROM KYNGHI
	GROUP BY TENDD);