----1
alter table CUNG_UNG add primary key(MA_NCC, MA_HANG, MA_DU_AN);

ALTER TABLE HANG_HOA ADD CHECK (mau='xam' OR mau='do' OR mau = 'trang' OR mau ='xanh');

----2
SELECT *
FROM HANG_HOA
WHERE MAU='xanh' OR MAU='do';

--3
SELECT distinct NCC.TEN_NCC
FROM HANG_HOA HH
JOIN CUNG_UNG CU ON HH.MA_HANG=CU.MA_HANG
JOIN NHA_CCAP NCC ON NCC.MA_NCC=CU.MA_NCC
JOIN DU_AN DA ON DA.MA_DU_AN=CU.MA_DU_AN
WHERE DA.TEN_DU_AN='tan an';

--4
Select TEN_NCC, COUNT(*)
FROM NHA_CCAP NCC
JOIN CUNG_UNG CU ON NCC.MA_NCC=CU.MA_NCC
GROUP BY TEN_NCC HAVING COUNT(*) > 4;

--5
SELECT NCC.TEN_NCC
FROM HANG_HOA HH
JOIN CUNG_UNG CU ON HH.MA_HANG = CU.MA_HANG
JOIN NHA_CCAP NCC ON NCC.MA_NCC=CU.MA_NCC
WHERE HH.MAU='trang'
INTERSECT
SELECT NCC.TEN_NCC
FROM HANG_HOA HH
JOIN CUNG_UNG CU ON HH.MA_HANG = CU.MA_HANG
JOIN NHA_CCAP NCC ON NCC.MA_NCC=CU.MA_NCC
WHERE HH.MAU='do';

-----6
SELECT TEN_NCC
FROM NHA_CCAP
WHERE MA_NCC IN (
SELECT MA_NCC
FROM CUNG_UNG
GROUP BY MA_NCC HAVING COUNT(DISTINCT MA_HANG) = (
SELECT COUNT(*)
FROM HANG_HOA
));